spring.application.name=msvc-ejecucionInspeccion
server.port=8030

spring.datasource.url=jdbc:mysql://localhost:3306/msvc_ejecucionInspeccion
spring.datasource.username=root
spring.datasource.password=100405
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.generate-ddl=true

logging.level.org.hibernate.SQL=debug